env:
  node: true

plugins:
  - 'prettier'

extends:
  - 'airbnb-base'
  - 'prettier'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: off
  import/extensions: off
  prettier/prettier: 'error'
